name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: "file:./test.db"

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
          NEXTAUTH_SECRET: "test-secret-32-chars-long-for-testing"
          NEXTAUTH_URL: "http://localhost:3000"
          GOOGLE_CLIENT_ID: "test-client-id"
          GOOGLE_CLIENT_SECRET: "test-client-secret"
          BILLING_PROVIDER: "lemon-squeezy"
          LEMON_SQUEEZY_WEBHOOK_SECRET: "test-webhook-secret"
          OPENAI_API_KEY: "test-openai-key"
          GTIN_PROVIDER: "upcitemdb"
          UPCITEMDB_USER_KEY: "test-upcitemdb-key"

  # Деплой через Vercel происходит автоматически при push в main
  # Этот workflow только проверяет качество кода
